VMC96API: examples/opto_line_sensor.c File Reference
opto_line_sensor.c File Reference
Example: Read Status from Opto Line Sensor.
#include <stdio.h>
#include <stdlib.h>
#include "vmc96api.h"
Functions
int main (int argc, char **argv)
Detailed Description
Example: Read Status from Opto Line Sensor.
Author
Tiago Ventura (tiago.nosp@m..ven.nosp@m.tura@.nosp@m.gmai.nosp@m.l.com)
Date
Dec.2018
Copyright (c) 2018 Tiago Ventura (tiago.nosp@m..ven.nosp@m.tura@.nosp@m.gmai.nosp@m.l.com)
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file opto_line_sensor.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 34 of file opto_line_sensor.c.
References VMC96_opto_line_sample_block_s::sample, vmc96_finish(), vmc96_get_error_code_string(), vmc96_initialize(), vmc96_motor_opto_line_status(), VMC96_OPTO_LINE_SAMPLE_BLOCK_LENGTH_MS, VMC96_OPTO_LINE_SAMPLE_LENGTH_MS, VMC96_OPTO_LINE_SAMPLES_PER_BLOCK, and VMC96_SUCCESS.