VMC96API: examples/scan_array.c File Reference
scan_array.c File Reference
Example: Scan Motor Array searching for installed motors.
#include <stdio.h>
#include <stdlib.h>
#include "vmc96api.h"
Functions
int main (int argc, char **argv)
Detailed Description
Example: Scan Motor Array searching for installed motors.
Author
Tiago Ventura (tiago.nosp@m..ven.nosp@m.tura@.nosp@m.gmai.nosp@m.l.com)
Date
Dec.2018
Copyright (c) 2018 Tiago Ventura (tiago.nosp@m..ven.nosp@m.tura@.nosp@m.gmai.nosp@m.l.com)
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file scan_array.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 34 of file scan_array.c.
References VMC96_motor_array_scan_result_s::array, VMC96_motor_array_scan_result_s::count, VMC96_motor_array_s::motor, vmc96_finish(), vmc96_get_error_code_string(), vmc96_initialize(), VMC96_MOTOR_ARRAY_COLUMNS_COUNT, VMC96_MOTOR_ARRAY_ROWS_COUNT, vmc96_motor_scan_array(), and VMC96_SUCCESS.