VMC96API: vmc96cli.c File Reference
vmc96cli.c File Reference
VMC96 Board Vending Machine Controller Command Line Interface.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include "vmc96api.h"
Classes
struct vmc96cli_arguments_s
Macros
#define VMC96CLI_CONTROLLER_GLOBAL (1)
#define VMC96CLI_CONTROLLER_RELAY1 (2)
#define VMC96CLI_CONTROLLER_RELAY2 (3)
#define VMC96CLI_CONTROLLER_MOTOR_ARRAY (4)
#define VMC96CLI_CONTROLLER_INVALID (-1)
#define VMC96CLI_CONTROLLER_NOT_SPECIFIED (-2)
#define VMC96CLI_COMMAND_RESET (1)
#define VMC96CLI_COMMAND_PING (2)
#define VMC96CLI_COMMAND_VERSION (3)
#define VMC96CLI_COMMAND_RELAY_CONTROL (4)
#define VMC96CLI_COMMAND_OPTO_LINE_STATUS (5)
#define VMC96CLI_COMMAND_MOTOR_RUN (6)
#define VMC96CLI_COMMAND_MOTOR_RUN_PAIR (7)
#define VMC96CLI_COMMAND_MOTOR_STOP_ALL (8)
#define VMC96CLI_COMMAND_MOTOR_STATUS (9)
#define VMC96CLI_COMMAND_ARRAY_SCAN (10)
#define VMC96CLI_COMMAND_GIVE_PULSE (11)
#define VMC96CLI_COMMAND_INVALID (-1)
#define VMC96CLI_COMMAND_NOT_SPECIFIED (-2)
#define VMC96CLI_SUCCESS (0)
#define VMC96CLI_ERROR_INVALID_ARGS (-1)
#define VMC96CLI_ERROR_COMMAND_FAILED (-2)
#define VMC96CLI_ERROR_ARGS_CONTROLLER_INVALID (-3)
#define VMC96CLI_ERROR_ARGS_CONTROLLER_NOT_SPECIFIED (-4)
#define VMC96CLI_ERROR_ARGS_COMMAND_INVALID (-5)
#define VMC96CLI_ERROR_ARGS_COMMAND_NOT_SPECIFIED (-6)
#define VMC96CLI_ERROR_ARGS_RELAY_STATE (-7)
#define VMC96CLI_ERROR_ARGS_MOTOR_ROW (-8)
#define VMC96CLI_ERROR_ARGS_MOTOR_COLUMN (-9)
#define VMC96CLI_ERROR_ARGS_MOTOR_COLUMN1 (-10)
#define VMC96CLI_ERROR_ARGS_MOTOR_COLUMN2 (-11)
#define VMC96CLI_ERROR_ARGS_DURATION (-12)
#define VMC96CLI_ARGUMENT_NOT_INITIALIZED (-1)
Typedefs
typedef struct vmc96cli_arguments_s vmc96cli_arguments_t
Functions
int main (int argc, char **argv)
Detailed Description
VMC96 Board Vending Machine Controller Command Line Interface.
Author
Tiago Ventura (tiago.nosp@m..ven.nosp@m.tura@.nosp@m.gmai.nosp@m.l.com)
Date
Dec.2018
Copyright (c) 2018 Tiago Ventura (tiago.nosp@m..ven.nosp@m.tura@.nosp@m.gmai.nosp@m.l.com)
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file vmc96cli.c.
Macro Definition Documentation
#define VMC96CLI_ARGUMENT_NOT_INITIALIZED (-1)
Definition at line 76 of file vmc96cli.c.
#define VMC96CLI_COMMAND_ARRAY_SCAN (10)
Definition at line 57 of file vmc96cli.c.
#define VMC96CLI_COMMAND_GIVE_PULSE (11)
Definition at line 58 of file vmc96cli.c.
#define VMC96CLI_COMMAND_INVALID (-1)
Definition at line 59 of file vmc96cli.c.
#define VMC96CLI_COMMAND_MOTOR_RUN (6)
Definition at line 53 of file vmc96cli.c.
#define VMC96CLI_COMMAND_MOTOR_RUN_PAIR (7)
Definition at line 54 of file vmc96cli.c.
#define VMC96CLI_COMMAND_MOTOR_STATUS (9)
Definition at line 56 of file vmc96cli.c.
#define VMC96CLI_COMMAND_MOTOR_STOP_ALL (8)
Definition at line 55 of file vmc96cli.c.
#define VMC96CLI_COMMAND_NOT_SPECIFIED (-2)
Definition at line 60 of file vmc96cli.c.
#define VMC96CLI_COMMAND_OPTO_LINE_STATUS (5)
Definition at line 52 of file vmc96cli.c.
#define VMC96CLI_COMMAND_PING (2)
Definition at line 49 of file vmc96cli.c.
#define VMC96CLI_COMMAND_RELAY_CONTROL (4)
Definition at line 51 of file vmc96cli.c.
#define VMC96CLI_COMMAND_RESET (1)
Definition at line 48 of file vmc96cli.c.
#define VMC96CLI_COMMAND_VERSION (3)
Definition at line 50 of file vmc96cli.c.
#define VMC96CLI_CONTROLLER_GLOBAL (1)
Definition at line 41 of file vmc96cli.c.
#define VMC96CLI_CONTROLLER_INVALID (-1)
Definition at line 45 of file vmc96cli.c.
#define VMC96CLI_CONTROLLER_MOTOR_ARRAY (4)
Definition at line 44 of file vmc96cli.c.
#define VMC96CLI_CONTROLLER_NOT_SPECIFIED (-2)
Definition at line 46 of file vmc96cli.c.
#define VMC96CLI_CONTROLLER_RELAY1 (2)
Definition at line 42 of file vmc96cli.c.
#define VMC96CLI_CONTROLLER_RELAY2 (3)
Definition at line 43 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_COMMAND_INVALID (-5)
Definition at line 67 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_COMMAND_NOT_SPECIFIED (-6)
Definition at line 68 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_CONTROLLER_INVALID (-3)
Definition at line 65 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_CONTROLLER_NOT_SPECIFIED (-4)
Definition at line 66 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_DURATION (-12)
Definition at line 74 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_MOTOR_COLUMN (-9)
Definition at line 71 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_MOTOR_COLUMN1 (-10)
Definition at line 72 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_MOTOR_COLUMN2 (-11)
Definition at line 73 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_MOTOR_ROW (-8)
Definition at line 70 of file vmc96cli.c.
#define VMC96CLI_ERROR_ARGS_RELAY_STATE (-7)
Definition at line 69 of file vmc96cli.c.
#define VMC96CLI_ERROR_COMMAND_FAILED (-2)
Definition at line 64 of file vmc96cli.c.
#define VMC96CLI_ERROR_INVALID_ARGS (-1)
Definition at line 63 of file vmc96cli.c.
#define VMC96CLI_SUCCESS (0)
Definition at line 62 of file vmc96cli.c.
Referenced by main().
Typedef Documentation
typedef struct vmc96cli_arguments_s vmc96cli_arguments_t
Definition at line 83 of file vmc96cli.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 661 of file vmc96cli.c.
References vmc96_finish(), vmc96_get_error_code_string(), vmc96_initialize(), VMC96_SUCCESS, and VMC96CLI_SUCCESS.